---

- block:
    - name: Post results
      import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{  ansible_distribution_version is version(expected[id], '>=') }}"
