---

- name: "{{ id }}.check"
  shell: |
    # if virtIP not configured, exit with fail
    cibadmin -Q --xpath "//primitive[@type='IPaddr2']/@type" || exit 1
    # if not grouped, exit with fail
    cibadmin -Q --xpath "//group/primitive[@type='IPaddr2']/@type" || exit 1
    # Check that following match expected, exit with error if any do not
    XPATH="//primitive[@type='IPaddr2']/operations/op"
    [[ $(cibadmin -Q --xpath "${XPATH} [@name='monitor']" | grep -oP 'interval="\K[^"]+') != "{{ expected[id + '.monitor_interval'] }}" ]] && exit 1
    [[ $(cibadmin -Q --xpath "${XPATH} [@name='monitor']" | grep -oP 'timeout="\K[^"]+') != "{{ expected[id + '.monitor_timeout'] }}" ]] && exit 1
    exit 0
  check_mode: false
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1

- block:
    - name: Post results
      import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
