---

- name: Set Test ID
  set_fact:
    test_id: '1.1.1'

- name: "Set other facts for {{ test_id }}"
  set_fact:
    test_mid: "1.1"
    test_name: "Corosync"
    test_desc: "Corosync Token is set to {{ expected[test_id] }}"
    test_remediation: "ansible"

- name: "{{ test_id }}.remediate"
  replace:
    path: /etc/corosync/corosync.conf
    regexp: '(\s+)token:(\s)[0-9]+?$'
    replace: '\1token: {{ expected[test_id] }}'
  register: config_updated

- import_role:
    name: corosync_restart
  when:
    - config_updated is changed
    - not ansible_check_mode

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is changed | ternary ('Failed','Passed') }}"
