// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/trento-project/trento/web/models"
)

// ChecksService is an autogenerated mock type for the ChecksService type
type ChecksService struct {
	mock.Mock
}

// GetChecksCatalog provides a mock function with given fields:
func (_m *ChecksService) GetChecksCatalog() ([]*models.Check, error) {
	ret := _m.Called()

	var r0 []*models.Check
	if rf, ok := ret.Get(0).(func() []*models.Check); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Check)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
