// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	hosts "github.com/trento-project/trento/internal/hosts"
)

// HostsService is an autogenerated mock type for the HostsService type
type HostsService struct {
	mock.Mock
}

// GetHostMetadata provides a mock function with given fields: host
func (_m *HostsService) GetHostMetadata(host string) (map[string]string, error) {
	ret := _m.Called(host)

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func(string) map[string]string); ok {
		r0 = rf(host)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(host)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHostsBySid provides a mock function with given fields: sid
func (_m *HostsService) GetHostsBySid(sid string) (hosts.HostList, error) {
	ret := _m.Called(sid)

	var r0 hosts.HostList
	if rf, ok := ret.Get(0).(func(string) hosts.HostList); ok {
		r0 = rf(sid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(hosts.HostList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
