// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package services

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/trento-project/trento/web/models"
)

// MockClustersService is an autogenerated mock type for the ClustersService type
type MockClustersService struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: filters
func (_m *MockClustersService) GetAll(filters map[string][]string) (models.ClusterList, error) {
	ret := _m.Called(filters)

	var r0 models.ClusterList
	if rf, ok := ret.Get(0).(func(map[string][]string) models.ClusterList); ok {
		r0 = rf(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.ClusterList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string][]string) error); ok {
		r1 = rf(filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
