// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package services

import (
	mock "github.com/stretchr/testify/mock"
	datapipeline "github.com/trento-project/trento/web/datapipeline"
)

// MockCollectorService is an autogenerated mock type for the CollectorService type
type MockCollectorService struct {
	mock.Mock
}

// StoreEvent provides a mock function with given fields: dataCollected
func (_m *MockCollectorService) StoreEvent(dataCollected *datapipeline.DataCollectedEvent) error {
	ret := _m.Called(dataCollected)

	var r0 error
	if rf, ok := ret.Get(0).(func(*datapipeline.DataCollectedEvent) error); ok {
		r0 = rf(dataCollected)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
