// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package services

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/trento-project/trento/web/models"
)

// MockHealthSummaryService is an autogenerated mock type for the HealthSummaryService type
type MockHealthSummaryService struct {
	mock.Mock
}

// GetHealthSummary provides a mock function with given fields:
func (_m *MockHealthSummaryService) GetHealthSummary() (models.HealthSummary, error) {
	ret := _m.Called()

	var r0 models.HealthSummary
	if rf, ok := ret.Get(0).(func() models.HealthSummary); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.HealthSummary)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
