// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package services

import (
	mock "github.com/stretchr/testify/mock"
	subscription "github.com/trento-project/trento/internal/subscription"
)

// MockSubscriptionsService is an autogenerated mock type for the SubscriptionsService type
type MockSubscriptionsService struct {
	mock.Mock
}

// GetHostSubscriptions provides a mock function with given fields: host
func (_m *MockSubscriptionsService) GetHostSubscriptions(host string) (subscription.Subscriptions, error) {
	ret := _m.Called(host)

	var r0 subscription.Subscriptions
	if rf, ok := ret.Get(0).(func(string) subscription.Subscriptions); ok {
		r0 = rf(host)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(subscription.Subscriptions)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(host)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubscriptionData provides a mock function with given fields:
func (_m *MockSubscriptionsService) GetSubscriptionData() (*SubscriptionData, error) {
	ret := _m.Called()

	var r0 *SubscriptionData
	if rf, ok := ret.Get(0).(func() *SubscriptionData); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SubscriptionData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
