// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package services

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/trento-project/trento/web/models"
)

// MockSubscriptionsService is an autogenerated mock type for the SubscriptionsService type
type MockSubscriptionsService struct {
	mock.Mock
}

// GetHostSubscriptions provides a mock function with given fields: host
func (_m *MockSubscriptionsService) GetHostSubscriptions(host string) ([]*models.SlesSubscription, error) {
	ret := _m.Called(host)

	var r0 []*models.SlesSubscription
	if rf, ok := ret.Get(0).(func(string) []*models.SlesSubscription); ok {
		r0 = rf(host)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.SlesSubscription)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(host)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPremiumData provides a mock function with given fields:
func (_m *MockSubscriptionsService) GetPremiumData() (*models.PremiumData, error) {
	ret := _m.Called()

	var r0 *models.PremiumData
	if rf, ok := ret.Get(0).(func() *models.PremiumData); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PremiumData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsTrentoPremium provides a mock function with given fields:
func (_m *MockSubscriptionsService) IsTrentoPremium() (bool, error) {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
