---

- name: set_global_results {{ test_id }}
  delegate_to: localhost
  set_fact:
    tests_meta_data: "{{ (tests_meta_data | default({})) | combine({test_id: {'desc': test_desc,'remediation': test_remediation,'mid': test_mid, 'name': test_name} }, recursive=True) }}"
