// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/trento-project/trento/web/models"

	service "github.com/trento-project/trento/web/service"
)

// IHostsService is an autogenerated mock type for the IHostsService type
type IHostsService struct {
	mock.Mock
}

// GetHosts provides a mock function with given fields: page, filters
func (_m *IHostsService) GetHosts(page *service.Page, filters map[string][]string) []models.Host {
	ret := _m.Called(page, filters)

	var r0 []models.Host
	if rf, ok := ret.Get(0).(func(*service.Page, map[string][]string) []models.Host); ok {
		r0 = rf(page, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Host)
		}
	}

	return r0
}

// GetHostsCount provides a mock function with given fields:
func (_m *IHostsService) GetHostsCount() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetHostsEnvironments provides a mock function with given fields:
func (_m *IHostsService) GetHostsEnvironments() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// GetHostsLandscapes provides a mock function with given fields:
func (_m *IHostsService) GetHostsLandscapes() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// GetHostsSAPSystems provides a mock function with given fields:
func (_m *IHostsService) GetHostsSAPSystems() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}
