// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	api "github.com/hashicorp/consul/api"

	mock "github.com/stretchr/testify/mock"
)

// Agent is an autogenerated mock type for the Agent type
type Agent struct {
	mock.Mock
}

// Reload provides a mock function with given fields:
func (_m *Agent) Reload() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceDeregister provides a mock function with given fields: serviceID
func (_m *Agent) ServiceDeregister(serviceID string) error {
	ret := _m.Called(serviceID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(serviceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceRegister provides a mock function with given fields: service
func (_m *Agent) ServiceRegister(service *api.AgentServiceRegistration) error {
	ret := _m.Called(service)

	var r0 error
	if rf, ok := ret.Get(0).(func(*api.AgentServiceRegistration) error); ok {
		r0 = rf(service)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTTL provides a mock function with given fields: checkID, note, status
func (_m *Agent) UpdateTTL(checkID string, note string, status string) error {
	ret := _m.Called(checkID, note, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(checkID, note, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
