// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	consul "github.com/trento-project/trento/internal/consul"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Catalog provides a mock function with given fields:
func (_m *Client) Catalog() consul.Catalog {
	ret := _m.Called()

	var r0 consul.Catalog
	if rf, ok := ret.Get(0).(func() consul.Catalog); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(consul.Catalog)
		}
	}

	return r0
}

// Health provides a mock function with given fields:
func (_m *Client) Health() consul.Health {
	ret := _m.Called()

	var r0 consul.Health
	if rf, ok := ret.Get(0).(func() consul.Health); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(consul.Health)
		}
	}

	return r0
}

// KV provides a mock function with given fields:
func (_m *Client) KV() consul.KV {
	ret := _m.Called()

	var r0 consul.KV
	if rf, ok := ret.Get(0).(func() consul.KV); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(consul.KV)
		}
	}

	return r0
}
