// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	api "github.com/hashicorp/consul/api"

	mock "github.com/stretchr/testify/mock"
)

// Health is an autogenerated mock type for the Health type
type Health struct {
	mock.Mock
}

// Node provides a mock function with given fields: node, q
func (_m *Health) Node(node string, q *api.QueryOptions) (api.HealthChecks, *api.QueryMeta, error) {
	ret := _m.Called(node, q)

	var r0 api.HealthChecks
	if rf, ok := ret.Get(0).(func(string, *api.QueryOptions) api.HealthChecks); ok {
		r0 = rf(node, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.HealthChecks)
		}
	}

	var r1 *api.QueryMeta
	if rf, ok := ret.Get(1).(func(string, *api.QueryOptions) *api.QueryMeta); ok {
		r1 = rf(node, q)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*api.QueryMeta)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, *api.QueryOptions) error); ok {
		r2 = rf(node, q)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Service provides a mock function with given fields: service, tag, passingOnly, q
func (_m *Health) Service(service string, tag string, passingOnly bool, q *api.QueryOptions) ([]*api.ServiceEntry, *api.QueryMeta, error) {
	ret := _m.Called(service, tag, passingOnly, q)

	var r0 []*api.ServiceEntry
	if rf, ok := ret.Get(0).(func(string, string, bool, *api.QueryOptions) []*api.ServiceEntry); ok {
		r0 = rf(service, tag, passingOnly, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*api.ServiceEntry)
		}
	}

	var r1 *api.QueryMeta
	if rf, ok := ret.Get(1).(func(string, string, bool, *api.QueryOptions) *api.QueryMeta); ok {
		r1 = rf(service, tag, passingOnly, q)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*api.QueryMeta)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string, bool, *api.QueryOptions) error); ok {
		r2 = rf(service, tag, passingOnly, q)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
