---

- name: "{{ id }}.check"
  shell: |
    #
    readlink /etc/products.d/baseproduct | grep -i "{{ expected [id] }}" || exit 1
    exit 0
  check_mode: false
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1

- block:
    - name: Post results
      import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
