// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package telemetry

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockInstallationIdAwareExtractor is an autogenerated mock type for the InstallationIdAwareExtractor type
type MockInstallationIdAwareExtractor struct {
	mock.Mock
}

// Extract provides a mock function with given fields:
func (_m *MockInstallationIdAwareExtractor) Extract() (interface{}, error) {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithInstallationID provides a mock function with given fields: _a0
func (_m *MockInstallationIdAwareExtractor) WithInstallationID(_a0 uuid.UUID) {
	_m.Called(_a0)
}
