// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package telemetry

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockPublisher is an autogenerated mock type for the Publisher type
type MockPublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: telemetryName, installationID, extractedTelemetry
func (_m *MockPublisher) Publish(telemetryName string, installationID uuid.UUID, extractedTelemetry interface{}) error {
	ret := _m.Called(telemetryName, installationID, extractedTelemetry)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, uuid.UUID, interface{}) error); ok {
		r0 = rf(telemetryName, installationID, extractedTelemetry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
