---

- name: "{{ id }}.check"
  shell: |
    sid=$(crm configure show | grep -m1 SID= | sed -e "s/.*SID=\(...\).*/\1/" | tr '[:lower:]' '[:upper:]')
    inst=$(crm configure show | grep -m1 InstanceNumber= | sed -e "s/.*InstanceNumber=\(..\).*/\1/")
    cat /usr/sap/${sid}/SYS/profile/${sid}_HDB${inst}_$(hostname) | grep "Autostart = 0" || exit 1
    exit 0
  check_mode: false
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1

- block:
    - name: Post results
      import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
