---

- name: "{{ id }}.check"
  shell: |
    cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/@type" > /dev/null 2>&1 || exit 0
    [[ $(crm_attribute -t crm_config -G -n concurrent-fencing --quiet) = "{{ expected[id] }}" ]] && exit 0
    exit 1
  check_mode: false
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1

- block:
    - name: Post results
      import_role:
        name: post-results
  vars:
    status: "{{ config_updated is not changed }}"
  when:
    - ansible_check_mode
