---

- name: "{{ id }}.check"
  shell: |
    for i in $(crm_node -l | cut -d' ' -f2); do
      if ! cat /etc/hosts |grep -q $i; then exit 1; fi
    done
    exit 0
  check_mode: false
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1

- block:
    - name: Post results
      import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
