# This playbook deploys a simple stand alone checker for SAP/HANS.

- hosts: all

  tasks:
    - name: include load_facts
      import_role:
        name: load_facts
      tags:
        - always

    - name: include 1.1.1 remediate
      import_role:
        name: '1.1.1'
      tags:
        - 1.1.1

    - name: include 1.1.1.runtime remediate
      import_role:
        name: '1.1.1.runtime'
      tags:
        - 1.1.1.runtime

    - name: include 1.2.1 remediate
      import_role:
        name: '1.2.1'
      tags:
        - 1.2.1

    - name: include 1.3.5 remediate
      import_role:
        name: '1.3.5'
      tags:
        - 1.3.5

    - name: set_global_results
      set_fact:
        global_results: "{{ hostvars.hana1.tests }}{{ hostvars.hana2.tests }}"
      run_once: yes

    - name: Set Ara Global Results
      ara_record:
        key: "Test_Restults"
        value: "{{ global_results | to_nice_json  }}"
      run_once: yes
      delegate_to: localhost
