---

- name: "{{ id }}.check"
  shell: |
    # Check that following match expected, exit with error if any do not
    [[ $(crm_attribute -t rsc_defaults -G -n resource-stickiness --quiet) != "{{ expected[id + '.resource_stickiness'] }}" ]] && exit 1
    [[ $(crm_attribute -t rsc_defaults -G -n migration-threshold --quiet) != "{{ expected[id + '.migration_threshold'] }}" ]] && exit 1
    exit 0
  check_mode: false
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1

- block:
    - name: Post results
      import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
